In [2]:
import pandas as pd

In [3]:
data = pd.read_csv("data/puzzle50000.csv")

In [4]:
print(len(data))

4557000

In [12]:
filtered_data = data[data['RatingDeviation'] <= 90]

In [13]:
len(filtered_data)

3543002

In [15]:
toSave = filtered_data[:50000]

In [16]:
toSave.to_csv("puzzle50000.csv", index=False)

In [4]:
data['FEN'][:5]

0    r6k/pp2r2p/4Rp1Q/3p4/8/1N1P2R1/PqP2bPP/7K b - ...
1    5rk1/1p3ppp/pq3b2/8/8/1P1Q1N2/P4PPP/3R2K1 w - ...
2         8/4R3/1p2P3/p4r2/P6p/1P3Pk1/4K3/8 w - - 1 64
3    r2qr1k1/b1p2ppp/pp4n1/P1P1p3/4P1n1/B2P2Pb/3NBP...
4               8/8/4k1p1/2KpP2p/5PP1/8/8/8 w - - 0 53
Name: FEN, dtype: object

In [5]:
data.head()

,PuzzleId,FEN,Moves,Rating,RatingDeviation,Popularity,NbPlays,Themes,GameUrl,OpeningTags,...,success_prob_blitz_1150,success_prob_blitz_1250,success_prob_blitz_1350,success_prob_blitz_1450,success_prob_blitz_1550,success_prob_blitz_1650,success_prob_blitz_1750,success_prob_blitz_1850,success_prob_blitz_1950,success_prob_blitz_2050
0,00008,r6k/pp2r2p/4Rp1Q/3p4/8/1N1P2R1/PqP2bPP/7K b - ...,f2g3 e6e7 b2b1 b3c1 b1c1 h6c1,1902,76,95,7226,crushing hangingPiece long middlegame,https://lichess.org/787zsVup/black#48,NaN,...,0.218818,0.209653,0.186691,0.164491,0.152678,0.140435,0.136796,0.129520,0.119234,0.117752
1,0000D,5rk1/1p3ppp/pq3b2/8/8/1P1Q1N2/P4PPP/3R2K1 w - ...,d3d6 f8d8 d6d8 f6d8,1512,74,96,29629,advantage endgame short,https://lichess.org/F8M8OS71#53,NaN,...,0.034210,0.028367,0.022817,0.018677,0.015565,0.012677,0.009887,0.008078,0.006526,0.004738
2,0008Q,8/4R3/1p2P3/p4r2/P6p/1P3Pk1/4K3/8 w - - 1 64,e7f7 f5e5 e2f1 e5e6,1300,75,90,666,advantage endgame rookEndgame short,https://lichess.org/MQSyb3KW#127,NaN,...,0.692399,0.689112,0.706355,0.714826,0.720929,0.719589,0.721771,0.710567,0.719568,0.685810
3,0009B,r2qr1k1/b1p2ppp/pp4n1/P1P1p3/4P1n1/B2P2Pb/3NBP...,b6c5 e2g4 h3g4 d1g4,1078,74,87,573,advantage middlegame short,https://lichess.org/4MWQCxQ6/black#32,Kings_Pawn_Game Kings_Pawn_Game_Leonardis_Vari...,...,0.673641,0.676497,0.679858,0.681578,0.672302,0.679798,0.660224,0.642372,0.629270,0.636599
4,000Vc,8/8/4k1p1/2KpP2p/5PP1/8/8/8 w - - 0 53,g4h5 g6h5 f4f5 e6e5 f5f6 e5f6,1575,80,75,97,crushing endgame long pawnEndgame,https://lichess.org/l6AejDMO#105,NaN,...,0.686770,0.704962,0.730225,0.752930,0.773452,0.788956,0.805194,0.819237,0.838152,0.852966

In [8]:
data[data["Themes"].isna() == True]

Empty DataFrame
Columns: [PuzzleId, FEN, Moves, Rating, RatingDeviation, Popularity, NbPlays, Themes, GameUrl, OpeningTags, success_prob_rapid_1050, success_prob_rapid_1150, success_prob_rapid_1250, success_prob_rapid_1350, success_prob_rapid_1450, success_prob_rapid_1550, success_prob_rapid_1650, success_prob_rapid_1750, success_prob_rapid_1850, success_prob_rapid_1950, success_prob_rapid_2050, success_prob_blitz_1050, success_prob_blitz_1150, success_prob_blitz_1250, success_prob_blitz_1350, success_prob_blitz_1450, success_prob_blitz_1550, success_prob_blitz_1650, success_prob_blitz_1750, success_prob_blitz_1850, success_prob_blitz_1950, success_prob_blitz_2050]
Index: []

[0 rows x 32 columns]